version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=v
      - RABBITMQ_DEFAULT_PASS=123456
    command: sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
    restart: on-failure
volumes:
  uploads:  # Define the shared volume
